### PR TITLE
volume-widget: open mixer on middle click

### PR DESCRIPTION
**Pull request by nuno-silva**

### CODE REVIEW

**Comment by floli** [comment]
It's a standalone GUI app.

**Comment by floli** [comment]
Why not use the right click instead? The middle click on touch pad is sometimes hard to emulate and the right click is not used yet.

**Comment by streetturtle** [comment]
@floli the right click shows a dropdown with a list of sources/sinks: 

img

**Comment by streetturtle** [comment]
Thanks @nuno-silva  👍

**Pull request merged**
