### PR TITLE
Simplified get_brightness_cmd and using gears.filesystem

### PR DESCRIPTION
**Pull request by shubham-cpp**
- `brightnessctl` already has (g)et option that will get current
  brightness value without any decoration

- Using `gfs.get_configuration_dir()` will return the awesomewm config
  directory. [Reference](https://awesomewm.org/doc/api/libraries/gears.filesystem.html#get_configuration_dir)

### CODE REVIEW

**Comment by streetturtle** [comment]
Hey! Thanks for the PR! I've been out of my linux laptop for quite a while - sorry for the delay. Would you mind resolve conflicts - it looks like it's just formatting.

**Comment by WiltonLoch** [comment]
Hello, the "brightnessctl get" output is not a percentage value, which is required by the widget update function. So when using the new get_brightness_cmd with brightnessctl, the arc update won't work.

**Comment by shubham-cpp** [comment]
This is a known issue for Intel cards, just searched on arch wiki.

**Comment by shubham-cpp** [comment]
Should we instead use a generic method for getting brightness instead of different commands for different programs
Something like should work instead of relying on external command
```bash
bash -c "expr $(cat /sys/class/backlight/*/brightness) \* 100 / $(cat /sys/class/backlight/*/max_brightness)"
```

**Comment by WiltonLoch** [comment]
Thanks for the information!
Since we have to rely on the external commands to set the value of the brightness anyway maybe it is better to keep using the tool-specific get command for consistency. I would suggest just rolling back the command previously employed for brightnessctl.
I personally will probably start using some of the other brightness control tools which apparently seem more reliable.

**Comment by shubham-cpp** [comment]
Ok, I'll do this on weekend

**Pull request merged**
