### PR TITLE
feat: migrate weather.lua to use WeatherAPI

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
When I looked into OpenWeatherMap 3.0 API they demanded credit card information even for their free tier. Therefore I decided to move to another provider with a generous tier.

In a first step I rewrote the current weather report (i.e. no forecast) to use it.

I haven't received any commentary on #442 so I don't know where your mind was going. If OpenWeatherMap phases out its 2.5 API and nobody else intends to use their 3.0 one, I offer to take this implementation instead.

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
@AlbeyAmakiir Thank you.

I've added a safeguard similar to the stderr case.
In my experience as web developer, _some_ web services sent out HTML instead of JSON when there's an Internal Server Error (think a Reverse Proxy in front of the app server is trying to be helpful). It could have been the case here.

@streetturtle The Luacheck fails over an unused variable in the APT widget. Shall I address it in this PR?

**Comment by streetturtle** [comment]
That would be amazing! Thanks!

**Comment by streetturtle** [comment]
I'll test it today/tomorrow and will let you know. Thank you for your work!

**Comment by streetturtle** [comment]
https://github.com/streetturtle/awesome-wm-widgets/issues/442#issuecomment-2183633251

**Comment by Ryuno-Ki** [comment]
@streetturtle I feel this is ready for another round of review

**Review by streetturtle — APPROVED** [review]

**Comment by vredesbyyrd** [comment]
@Ryuno-Ki 

I much appreciate you taking the time to do this. WeatherAPI looks pretty nice! 

Looking at the `icon_map` table, I'm wondering if there is anyway we can have the current weather icon distinguish between night and day?  The api returns a boolean for `is_day`, which might be helpful? It just seems a bit jarring to see a sunny icon when it's dark outside.

I may dig into this myself, but any thoughts you might have would be very appreciated!

**Comment by Ryuno-Ki** [comment]
Thank you.

Day/Night icons will be part of https://github.com/streetturtle/awesome-wm-widgets/pull/455

**Pull request merged**
