### PR TITLE
Enable storing creds via env vars

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by streetturtle** [comment]
Hi! Sorry for the late reply.
Thanks for pr!
And just for info, I am currently working on externalising widget config, so that it would be possible to define it in rc.lua, like this: https://github.com/streetturtle/awesome-wm-widgets/tree/74-externalize-config/weather-widget

**Comment by webknjaz** [comment]
I still prefer env vars because they allow separation of the data from logic.

**Comment by streetturtle** [comment]
But you still will be able to use env vars in the widget constructor, I guess:

```lua
weather_widget({
    api_key = os.getenv('AWW_WEATHER_API_KEY'),
}),
```

**Comment by webknjaz** [comment]
Fair enough.

**Pull request merged**
