### PR TITLE
Fix the syntax of passing multiline args @ weather

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by streetturtle** [comment]
https://github.com/streetturtle/awesome-wm-widgets/compare/50fbb5529901...3e189049e1f5

**Comment by webknjaz** [comment]
Right... FWIW this one also works while allowing to keep the trailing comma.

**Comment by streetturtle** [comment]
I don't think it works, I'll close this pr, if you don't mind :smiley:

**Comment by webknjaz** [comment]
Well, it worked locally, I think

**Pull request closed without merging**
