### PR TITLE
Query weather with async timeouts

### LINKED ISSUE #81: [BUG] Weather widget uses a blocking HTTP call
This creates problems and freezes Awesome whenever the Internet connection is unstable.

The workaround is to asynchronously spawn curl subprocess: https://github.com/vicious-widgets/vicious/blob/9cf9e99/widgets/weather_all.lua#L95

### PR DESCRIPTION
**Pull request by webknjaz**
Fixes #81

### CODE REVIEW

**Comment by webknjaz** [comment]
@streetturtle?

**Comment by webknjaz** [comment]
What do you think?

**Comment by streetturtle** [comment]
I'll test it this weekend (just in case) and will merge. Sorry for the delay

**Comment by webknjaz** [comment]
Sure, thanks!

I'm using this for almost 3 weeks.

For me, it prevents long freezes which happened from time to time. Sometimes, I even got a completely frozen WM without any ability to click on things outside of the active window for hours. Most of the time, after waiting for a long time, I'd give up and just kill the WM because I could do nothing.

With this patch, if there's some network instability, I only get very rare freezes with their durations being fractions of a second. Most of the time, I wouldn't even notice anything.

**Comment by streetturtle** [comment]
That's awesome! Thanks! And sorry again for the delay

**Pull request merged**
