### PR TITLE
fix(apt-widget): Fixed nil value (buttons) -Also replaces awful.util with gears

### PR DESCRIPTION
**Pull request by HamishFleming**
Fix for the issue mentioned here:  Docker widget attempt to call a nil value (method 'buttons') #242 

The issue seemed to come from the call of apt_widget:buttons not behaving as expected.

I'm not overly confident with my lua so there may be a better way, but a quick fix is wrapping the widget in another wibox which seems to work.

PR also contains formatting and replacing the calls to awful.util with calls to gears.

I have a few extra changes in the version in my awesome config that wouldn't make sense to include in the PR, but to fix the issues with larger monitors/multiple screens this is the line for placement I am using 

`				awful.placement.top_right(wibox_popup, { margins = { top = dpi(30) }})
`

dropping the parent = mouse handles placing the icon far to the right on the bar

### CODE REVIEW

**Comment by streetturtle** [comment]
Sorry for the delay, I'll need some time to test the changes and then I will merge it. Thank you! :+1:

**Comment by floli** [comment]
Hey, has there been any progress on that? I just tried the docker widget again and stil have the bug #242. Best Thanks!

**Comment by vulekhanh** [comment]
I just installed docker widget and I got the bug #242 . The error is
 ``` docker.lua:353: attempt to call a nil value (method 'buttons')```
 I don't know if I'm missing any dependencies in awesomewm or not.

**Comment by floli** [comment]
Just tried latest master of `awesome-wm-widgets´, still getting:
```
docker.lua:372: attempt to call a nil value (method 'buttons')
```

**Comment by streetturtle** [comment]
https://github.com/streetturtle/awesome-wm-widgets/issues/242#issuecomment-1639171438

**Pull request merged**
