### PR TITLE
Ability to resize battery-widget and volume-widget

### PR DESCRIPTION
**Pull request by TheBrainScrambler**
Hello, I just want to warn you that this is my first pull request ;)

So I focused on these two widgets, and noticed that there was no ability to resize them, and this can lead to too small icons in case of my config. The only way actually was to modify the code to resize. So I decided to modify the code and send this pull request. I documented the changes I made in each README of each widget (just modified the table). Those are actually small changes, but can be useful.

### CODE REVIEW

**Comment by TheBrainScrambler** [comment]
As this is open for a while, I added another commit for my personal purpose, "Changed hardcoded PATH_TO_ICONS variables in mpdarc", but ignore this one.

**Comment by streetturtle** [comment]
Thank you for the PR, I am not ready to merge it now, just need some time to think, as maybe there is some better way to resize the icon's container. What exactly was you problem with it? Is your wibar is too high/wide? Can you maybe share a screenshot of it?

Also I cannot ignore a commit from a pr (I think), so you should revert it by yourself.

**Comment by TheBrainScrambler** [comment]
As said above, the problem is that the widgets said above are too small on my bar. My font size is 11 instead of the default. If you want all the details about my config, have a look at https://github.com/TheBrainScrambler/dotfiles. And sorry for the commit, I will revert it if you plan to merge this.

**Comment by TheBrainScrambler** [comment]
Ok it is done, I "reverted" the commit with a hardcoded path by instead being able to set it as a parameter, and I mentionned the path_to_icon parameter in the README of volume-widget. So, I'm just waiting for your feedback, I'm done.

**Comment by TheBrainScrambler** [comment]
Hello, it's being a long time. Do you plan to merge it or do you have a better idea / just don't want to implement it ?
I would like to know if I can close it

**Comment by streetturtle** [comment]
Sorry, completely forgot about it.

Regarding the volume widget, I am currently reimplementing it, could you please try this one: https://github.com/streetturtle/awesome-wm-widgets/tree/master/experiments/volume and let me know if it works for you in terms of size. 

Regarding the problem you have with too small icons - I don't think that resizing icons is the right solution. The better way would be to override the icon with a bigger one. What do you think?

**Comment by TheBrainScrambler** [comment]
Sorry, I can't test it anymore, since I don't use AwesomeWM anymore. But I still think people should be able to resize icons in case they also have this problem.
Yes, what I did was kind of hacky, it might be indeed a good solution.
Also a bit unrelated, but you should also place the path to the icons in the configuration instead of hardcoding it. That was another problem I encountered and solved by hacking.

**Comment by TheBrainScrambler** [comment]
Closing this due to inactivity

**Pull request closed without merging**
